  export const top30_default = [
    { company: 'Apple Inc.', ticker: 'AAPL', marketCap: '2.65T', stockPrice: '$170.55' },
    { company: 'Microsoft Corp.', ticker: 'MSFT', marketCap: '2.50T', stockPrice: '$340.12' },
    { company: 'Saudi Aramco', ticker: '2222.SR', marketCap: '2.00T', stockPrice: 'SAR 36.85' },
    { company: 'Alphabet Inc.', ticker: 'GOOGL', marketCap: '1.65T', stockPrice: '$140.23' },
    { company: 'Amazon.com Inc.', ticker: 'AMZN', marketCap: '1.40T', stockPrice: '$130.42' },
    { company: 'Tesla Inc.', ticker: 'TSLA', marketCap: '950B', stockPrice: '$865.32' },
    { company: 'Berkshire Hathaway Inc.', ticker: 'BRK.B', marketCap: '750B', stockPrice: '$334.45' },
    { company: 'NVIDIA Corp.', ticker: 'NVDA', marketCap: '730B', stockPrice: '$470.09' },
    { company: 'Meta Platforms Inc.', ticker: 'META', marketCap: '700B', stockPrice: '$280.19' },
    { company: 'Johnson & Johnson', ticker: 'JNJ', marketCap: '630B', stockPrice: '$170.03' },
    { company: 'Visa Inc.', ticker: 'V', marketCap: '620B', stockPrice: '$243.27' },
    { company: 'Procter & Gamble Co.', ticker: 'PG', marketCap: '580B', stockPrice: '$154.60' },
    { company: 'UnitedHealth Group Inc.', ticker: 'UNH', marketCap: '570B', stockPrice: '$515.38' },
    { company: 'JPMorgan Chase & Co.', ticker: 'JPM', marketCap: '560B', stockPrice: '$150.95' },
    { company: 'Walmart Inc.', ticker: 'WMT', marketCap: '510B', stockPrice: '$153.24' },
    { company: 'Mastercard Inc.', ticker: 'MA', marketCap: '500B', stockPrice: '$375.11' },
    { company: 'Intel Corp.', ticker: 'INTC', marketCap: '485B', stockPrice: '$40.52' },
    { company: 'The Home Depot Inc.', ticker: 'HD', marketCap: '470B', stockPrice: '$350.78' },
    { company: 'Coca-Cola Co.', ticker: 'KO', marketCap: '460B', stockPrice: '$62.23' },
    { company: 'Pfizer Inc.', ticker: 'PFE', marketCap: '450B', stockPrice: '$41.87' },
    { company: 'Chevron Corp.', ticker: 'CVX', marketCap: '440B', stockPrice: '$172.65' },
    { company: 'Cisco Systems Inc.', ticker: 'CSCO', marketCap: '430B', stockPrice: '$56.20' },
    { company: 'Oracle Corp.', ticker: 'ORCL', marketCap: '420B', stockPrice: '$104.15' },
    { company: 'IBM Corp.', ticker: 'IBM', marketCap: '400B', stockPrice: '$135.45' },
    { company: 'Exxon Mobil Corp.', ticker: 'XOM', marketCap: '390B', stockPrice: '$124.75' },
    { company: 'Adobe Inc.', ticker: 'ADBE', marketCap: '380B', stockPrice: '$597.12' },
    { company: 'Salesforce.com Inc.', ticker: 'CRM', marketCap: '370B', stockPrice: '$224.91' },
    { company: 'Broadcom Inc.', ticker: 'AVGO', marketCap: '360B', stockPrice: '$887.29' },
    { company: 'Netflix Inc.', ticker: 'NFLX', marketCap: '350B', stockPrice: '$501.83' },
    { company: 'United Parcel Service Inc.', ticker: 'UPS', marketCap: '340B', stockPrice: '$176.59' },
    { company: 'Qualcomm Inc.', ticker: 'QCOM', marketCap: '330B', stockPrice: '$138.27' },
    { company: 'PayPal Holdings Inc.', ticker: 'PYPL', marketCap: '320B', stockPrice: '$252.14' },
    { company: 'Texas Instruments Inc.', ticker: 'TXN', marketCap: '310B', stockPrice: '$194.50' },
    { company: 'Goldman Sachs Group Inc.', ticker: 'GS', marketCap: '300B', stockPrice: '$392.25' },
];

export const Devon_default = {
    name: "Devon Fennell",
    DOB: '06/09/2001',
    phoneNumber: '229-302-1229',
    userName: "Devon The Investor",
    email: "devon@contact.mail", 
    password: "p@ssw0rd",
    
};
