import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from '@/components/contexts/AuthContext';
import { MarketProvider } from "@/components/contexts/MarketContext";
import { SelectionProvider } from "@/components/contexts/SelectionContext";
import { ExperimentProvider } from "@/components/contexts/ExperimentContext";
import { UserProvider } from "@/components/contexts/UserContext";

export const metadata: Metadata = {
  title: "Next Investment",
  description: "Generated by create next app",
  icons: {
    icon: "/public/vercel.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ExperimentProvider>
        <SelectionProvider>
          <MarketProvider>
            <UserProvider>
              <AuthProvider>
                <body className="h-lvh bg-gray-900">{children}</body>
              </AuthProvider>
            </UserProvider>
          </MarketProvider>
        </SelectionProvider>
      </ExperimentProvider>
    </html>
  );
}
