import type { Metadata } from "next";
import "./globals.css";
import { InvestorProvider } from '@/components/contexts/InvestorContext';
import { AuthProvider } from '@/components/contexts/AuthContext';
import { MarketProvider } from "@/components/contexts/MarketContext";

export const metadata: Metadata = {
  title: "Next Investment",
  description: "Generated by create next app",
  icons: {
    icon: "/public/vercel.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <MarketProvider>
          <InvestorProvider>
            <body className="bg-gray-950 relative flex-1">{children}</body>
          </InvestorProvider>
        </MarketProvider>
      </AuthProvider>
    </html>
  );
}
