import type { Metadata } from "next";
import "./globals.css";
import { InvestorProvider } from '@/components/contexts/InvestorContext';
import { AuthProvider } from '@/components/contexts/AuthContext';
import { MarketProvider } from "@/components/contexts/MarketContext";
import { SelectionProvider } from "@/components/contexts/SelectionContext";

export const metadata: Metadata = {
  title: "Next Investment",
  description: "Generated by create next app",
  icons: {
    icon: "/public/vercel.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SelectionProvider>
        <AuthProvider>
          <MarketProvider>
            <InvestorProvider>
              <body className="h-lvh bg-gray-900">{children}</body>
            </InvestorProvider>
          </MarketProvider>
        </AuthProvider>
      </SelectionProvider>
    </html>
  );
}
