import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { InvestorProvider } from "@/components/contexts/InvestorContext"

export const metadata: Metadata = {
  title: "Next Investment",
  description: "Generated by create next app",
  icons: {
    icon: "/public/vercel.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <InvestorProvider>
        <body>{children}</body>
      </InvestorProvider>
    </html>
  );
}
